/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarUnidadeOrg.java
 *
 * Created on 22/01/2012, 18:23:52
 */
package view;

import controller.SistemaCadUniOrg;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabiene
 */
public class CadastrarUnidadeOrg extends javax.swing.JFrame {

    /** Creates new form CadastrarUnidadeOrg */
    public CadastrarUnidadeOrg() {
        initComponents();
        
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage("src/Imagem/logo.png");
            setIconImage(icon);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "Erro!", 0);
            
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeSistema = new javax.swing.JLabel();
        identificadorTela = new javax.swing.JLabel();
        nomeUnidadeCad = new javax.swing.JLabel();
        campoNomeUnidCad = new javax.swing.JTextField();
        enviarUnidCad = new javax.swing.JButton();
        cancelarUnidCad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Unidade de Órgão Público");

        nomeSistema.setFont(new java.awt.Font("Calibri", 1, 24));
        nomeSistema.setForeground(new java.awt.Color(102, 102, 102));
        nomeSistema.setText("SISTEMA DE MONITORAMENTO GERENCIAL - RJ");

        identificadorTela.setFont(new java.awt.Font("Calibri", 1, 18));
        identificadorTela.setText("Cadastrar Unidade de Órgão Público #");

        nomeUnidadeCad.setFont(new java.awt.Font("Calibri", 1, 18));
        nomeUnidadeCad.setText("Nome da Unidade:");

        enviarUnidCad.setText("Enviar");
        enviarUnidCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarUnidCadActionPerformed(evt);
            }
        });

        cancelarUnidCad.setText("Cancelar");
        cancelarUnidCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUnidCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(nomeSistema)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(identificadorTela, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(nomeUnidadeCad)
                .addGap(253, 253, 253))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(campoNomeUnidCad, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(cancelarUnidCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarUnidCad)
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nomeSistema)
                .addGap(18, 18, 18)
                .addComponent(identificadorTela)
                .addGap(85, 85, 85)
                .addComponent(nomeUnidadeCad)
                .addGap(18, 18, 18)
                .addComponent(campoNomeUnidCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarUnidCad)
                    .addComponent(cancelarUnidCad))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void enviarUnidCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarUnidCadActionPerformed
// TODO add your handling code here:
    
    SistemaCadUniOrg sistema = new SistemaCadUniOrg();
    int codUnidade = 0;
    String nomeUnidade;
    
    nomeUnidade = campoNomeUnidCad.getText();
    
    if(nomeUnidade.isEmpty()){

           String msg = "Campos obrigatórios precisam ser preenchidos!";
           JOptionPane.showMessageDialog(null, msg);
       }else{

        sistema.inserirUnidade(codUnidade, nomeUnidade);

        int CodUnidadeOperacional = sistema.maiorCODUnidadeOperacional();
        
        String beleza = "Ocorrência inserida com sucesso \n Código da Ocorrência: " + CodUnidadeOperacional;

        JOptionPane.showMessageDialog(null, beleza);

        this.limparTela();

        }
    
    
    
}//GEN-LAST:event_enviarUnidCadActionPerformed

private void cancelarUnidCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUnidCadActionPerformed
    
          if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja fazer LOGOFF?", "ATENÇÂO", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
            SistemaCadUniOrg sistema = new SistemaCadUniOrg();
            sistema.iniciarPrograma();
        }
    
}//GEN-LAST:event_cancelarUnidCadActionPerformed
        public void limparTela(){
            campoNomeUnidCad.setText("");
        }
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    
    public void iniciarTelaCadUnidOrg(CadastrarUnidadeOrg tela){
        
        tela.setLayout(new FlowLayout());
        tela.setVisible(true);
        tela.pack();
 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomeUnidCad;
    private javax.swing.JButton cancelarUnidCad;
    private javax.swing.JButton enviarUnidCad;
    private javax.swing.JLabel identificadorTela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeSistema;
    private javax.swing.JLabel nomeUnidadeCad;
    // End of variables declaration//GEN-END:variables
}
